from src.model.bart_pg import BARTPointModel
from src.model.discriminator import RCDiscriminator
from src.task.faithful_summary_task import FaithfulSummarizationTask
from src.criterion.loss import LabelSmoothedCrossEntropyCriterion